utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Client.ApplicationServices.Carts;
using utb_eshop_patek.Domain.Constants;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public CartsController(
            ICartApplicationService cartApplicationService,
            ISecurityApplicationService securityApplicationService
            )
        {
            _cartApplicationService = cartApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = _cartApplicationService.GetIndexViewModel(GetTrackingCode());

            var user = await _securityApplicationService.GetCurrentUser(User);
            vm.UserID = user?.Id;
            vm.Login = user?.Email;

            return View(vm);
        }

        [HttpPost]
        public JsonResult AddToCart(int id, int amount)
        {
            var cartItem = _cartApplicationService.AddToCart(id, amount, GetTrackingCode());
            return Json(cartItem);
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            _cartApplicationService.RemoveFromCart(id, GetTrackingCode());
            return Json("success");
        }

        private string GetTrackingCode()
        {
            var utc = Request.Cookies[Cookies.UserTrackingCode];
            if (utc != null)
                return utc;

            var guid = Guid.NewGuid().ToString();
            var options = new CookieOptions();
            options.Expires = DateTime.Now.AddYears(1);

            Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);
            return guid;
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Client.ApplicationServices.Orders;
using utb_eshop_patek.Domain.Constants;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class OrdersController : Controller
    {
        private readonly IOrderApplicationService _orderApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public OrdersController(
            IOrderApplicationService orderApplicationService,
            ISecurityApplicationService securityApplicationService)
        {
            _orderApplicationService = orderApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            var user = await _securityApplicationService.GetCurrentUser(User);
            _orderApplicationService.CreateOrder(user.Id, Request.Cookies[Cookies.UserTrackingCode]);

            return RedirectToAction(nameof(Index));
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Carts/Index.cshtml
@model utb_eshop_patek.Application.Client.ViewModels.Carts.IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Košík</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Název
            </th>
            <th>
                Obrázek
            </th>
            <th>
                Množství
            </th>
            <th>
                Cena
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CartItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    <img src="@item.ImageUrl" class="image-thumbnail" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>
        }
    </tbody>
</table>

<h3 class="col-lg-offset-10">
    Celkem: € @Model.Total
</h3>
@if (Model.UserID.HasValue && Model.CartItems.Count > 0)
{
    <a class="btn btn-success col-lg-offset-10" asp-controller="Orders" asp-action="Create">
        Objednat
    </a>
}